package nba.clippers.rtwork.db.mapper;

import java.util.List;
import nba.clippers.rtwork.db.entity.ManagerInfo;
import nba.clippers.rtwork.modelExample.ManagerInfoExample;
import org.apache.ibatis.annotations.Param;

public interface ManagerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    long countByExample(ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    int deleteByExample(ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    int insert(ManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    int insertSelective(ManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    List<ManagerInfo> selectByExample(ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    ManagerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    int updateByExampleSelective(@Param("record") ManagerInfo record, @Param("example") ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    int updateByExample(@Param("record") ManagerInfo record, @Param("example") ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    int updateByPrimaryKeySelective(ManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    int updateByPrimaryKey(ManagerInfo record);
}