package nba.clippers.rtwork.modelExample;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class BussOpportunityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public BussOpportunityExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBussopNameIsNull() {
            addCriterion("bussop_name is null");
            return (Criteria) this;
        }

        public Criteria andBussopNameIsNotNull() {
            addCriterion("bussop_name is not null");
            return (Criteria) this;
        }

        public Criteria andBussopNameEqualTo(String value) {
            addCriterion("bussop_name =", value, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameNotEqualTo(String value) {
            addCriterion("bussop_name <>", value, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameGreaterThan(String value) {
            addCriterion("bussop_name >", value, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameGreaterThanOrEqualTo(String value) {
            addCriterion("bussop_name >=", value, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameLessThan(String value) {
            addCriterion("bussop_name <", value, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameLessThanOrEqualTo(String value) {
            addCriterion("bussop_name <=", value, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameLike(String value) {
            addCriterion("bussop_name like", value, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameNotLike(String value) {
            addCriterion("bussop_name not like", value, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameIn(List<String> values) {
            addCriterion("bussop_name in", values, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameNotIn(List<String> values) {
            addCriterion("bussop_name not in", values, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameBetween(String value1, String value2) {
            addCriterion("bussop_name between", value1, value2, "bussopName");
            return (Criteria) this;
        }

        public Criteria andBussopNameNotBetween(String value1, String value2) {
            addCriterion("bussop_name not between", value1, value2, "bussopName");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNull() {
            addCriterion("client_name is null");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNotNull() {
            addCriterion("client_name is not null");
            return (Criteria) this;
        }

        public Criteria andClientNameEqualTo(String value) {
            addCriterion("client_name =", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotEqualTo(String value) {
            addCriterion("client_name <>", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThan(String value) {
            addCriterion("client_name >", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThanOrEqualTo(String value) {
            addCriterion("client_name >=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThan(String value) {
            addCriterion("client_name <", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThanOrEqualTo(String value) {
            addCriterion("client_name <=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLike(String value) {
            addCriterion("client_name like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotLike(String value) {
            addCriterion("client_name not like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameIn(List<String> values) {
            addCriterion("client_name in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotIn(List<String> values) {
            addCriterion("client_name not in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameBetween(String value1, String value2) {
            addCriterion("client_name between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotBetween(String value1, String value2) {
            addCriterion("client_name not between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameIsNull() {
            addCriterion("market_manager_name is null");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameIsNotNull() {
            addCriterion("market_manager_name is not null");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameEqualTo(String value) {
            addCriterion("market_manager_name =", value, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameNotEqualTo(String value) {
            addCriterion("market_manager_name <>", value, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameGreaterThan(String value) {
            addCriterion("market_manager_name >", value, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameGreaterThanOrEqualTo(String value) {
            addCriterion("market_manager_name >=", value, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameLessThan(String value) {
            addCriterion("market_manager_name <", value, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameLessThanOrEqualTo(String value) {
            addCriterion("market_manager_name <=", value, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameLike(String value) {
            addCriterion("market_manager_name like", value, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameNotLike(String value) {
            addCriterion("market_manager_name not like", value, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameIn(List<String> values) {
            addCriterion("market_manager_name in", values, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameNotIn(List<String> values) {
            addCriterion("market_manager_name not in", values, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameBetween(String value1, String value2) {
            addCriterion("market_manager_name between", value1, value2, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andMarketManagerNameNotBetween(String value1, String value2) {
            addCriterion("market_manager_name not between", value1, value2, "marketManagerName");
            return (Criteria) this;
        }

        public Criteria andBussopStatusIsNull() {
            addCriterion("bussop_status is null");
            return (Criteria) this;
        }

        public Criteria andBussopStatusIsNotNull() {
            addCriterion("bussop_status is not null");
            return (Criteria) this;
        }

        public Criteria andBussopStatusEqualTo(String value) {
            addCriterion("bussop_status =", value, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusNotEqualTo(String value) {
            addCriterion("bussop_status <>", value, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusGreaterThan(String value) {
            addCriterion("bussop_status >", value, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusGreaterThanOrEqualTo(String value) {
            addCriterion("bussop_status >=", value, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusLessThan(String value) {
            addCriterion("bussop_status <", value, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusLessThanOrEqualTo(String value) {
            addCriterion("bussop_status <=", value, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusLike(String value) {
            addCriterion("bussop_status like", value, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusNotLike(String value) {
            addCriterion("bussop_status not like", value, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusIn(List<String> values) {
            addCriterion("bussop_status in", values, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusNotIn(List<String> values) {
            addCriterion("bussop_status not in", values, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusBetween(String value1, String value2) {
            addCriterion("bussop_status between", value1, value2, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andBussopStatusNotBetween(String value1, String value2) {
            addCriterion("bussop_status not between", value1, value2, "bussopStatus");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buss_opportunity
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 08 14:38:39 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}