package nba.clippers.rtwork.modelExample;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjectInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public ProjectInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectAmountIsNull() {
            addCriterion("project_amount is null");
            return (Criteria) this;
        }

        public Criteria andProjectAmountIsNotNull() {
            addCriterion("project_amount is not null");
            return (Criteria) this;
        }

        public Criteria andProjectAmountEqualTo(BigDecimal value) {
            addCriterion("project_amount =", value, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectAmountNotEqualTo(BigDecimal value) {
            addCriterion("project_amount <>", value, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectAmountGreaterThan(BigDecimal value) {
            addCriterion("project_amount >", value, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("project_amount >=", value, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectAmountLessThan(BigDecimal value) {
            addCriterion("project_amount <", value, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("project_amount <=", value, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectAmountIn(List<BigDecimal> values) {
            addCriterion("project_amount in", values, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectAmountNotIn(List<BigDecimal> values) {
            addCriterion("project_amount not in", values, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("project_amount between", value1, value2, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("project_amount not between", value1, value2, "projectAmount");
            return (Criteria) this;
        }

        public Criteria andProjectSourceIsNull() {
            addCriterion("project_source is null");
            return (Criteria) this;
        }

        public Criteria andProjectSourceIsNotNull() {
            addCriterion("project_source is not null");
            return (Criteria) this;
        }

        public Criteria andProjectSourceEqualTo(Integer value) {
            addCriterion("project_source =", value, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectSourceNotEqualTo(Integer value) {
            addCriterion("project_source <>", value, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectSourceGreaterThan(Integer value) {
            addCriterion("project_source >", value, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectSourceGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_source >=", value, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectSourceLessThan(Integer value) {
            addCriterion("project_source <", value, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectSourceLessThanOrEqualTo(Integer value) {
            addCriterion("project_source <=", value, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectSourceIn(List<Integer> values) {
            addCriterion("project_source in", values, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectSourceNotIn(List<Integer> values) {
            addCriterion("project_source not in", values, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectSourceBetween(Integer value1, Integer value2) {
            addCriterion("project_source between", value1, value2, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectSourceNotBetween(Integer value1, Integer value2) {
            addCriterion("project_source not between", value1, value2, "projectSource");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNull() {
            addCriterion("project_type is null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNotNull() {
            addCriterion("project_type is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeEqualTo(String value) {
            addCriterion("project_type =", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotEqualTo(String value) {
            addCriterion("project_type <>", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThan(String value) {
            addCriterion("project_type >", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("project_type >=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThan(String value) {
            addCriterion("project_type <", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThanOrEqualTo(String value) {
            addCriterion("project_type <=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLike(String value) {
            addCriterion("project_type like", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotLike(String value) {
            addCriterion("project_type not like", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIn(List<String> values) {
            addCriterion("project_type in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotIn(List<String> values) {
            addCriterion("project_type not in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeBetween(String value1, String value2) {
            addCriterion("project_type between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotBetween(String value1, String value2) {
            addCriterion("project_type not between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectLevelIsNull() {
            addCriterion("project_level is null");
            return (Criteria) this;
        }

        public Criteria andProjectLevelIsNotNull() {
            addCriterion("project_level is not null");
            return (Criteria) this;
        }

        public Criteria andProjectLevelEqualTo(String value) {
            addCriterion("project_level =", value, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelNotEqualTo(String value) {
            addCriterion("project_level <>", value, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelGreaterThan(String value) {
            addCriterion("project_level >", value, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelGreaterThanOrEqualTo(String value) {
            addCriterion("project_level >=", value, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelLessThan(String value) {
            addCriterion("project_level <", value, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelLessThanOrEqualTo(String value) {
            addCriterion("project_level <=", value, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelLike(String value) {
            addCriterion("project_level like", value, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelNotLike(String value) {
            addCriterion("project_level not like", value, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelIn(List<String> values) {
            addCriterion("project_level in", values, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelNotIn(List<String> values) {
            addCriterion("project_level not in", values, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelBetween(String value1, String value2) {
            addCriterion("project_level between", value1, value2, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectLevelNotBetween(String value1, String value2) {
            addCriterion("project_level not between", value1, value2, "projectLevel");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateIsNull() {
            addCriterion("project_initiation_date is null");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateIsNotNull() {
            addCriterion("project_initiation_date is not null");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateEqualTo(Date value) {
            addCriterionForJDBCDate("project_initiation_date =", value, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("project_initiation_date <>", value, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateGreaterThan(Date value) {
            addCriterionForJDBCDate("project_initiation_date >", value, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("project_initiation_date >=", value, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateLessThan(Date value) {
            addCriterionForJDBCDate("project_initiation_date <", value, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("project_initiation_date <=", value, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateIn(List<Date> values) {
            addCriterionForJDBCDate("project_initiation_date in", values, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("project_initiation_date not in", values, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("project_initiation_date between", value1, value2, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitiationDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("project_initiation_date not between", value1, value2, "projectInitiationDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateIsNull() {
            addCriterion("planned_acceptance_date is null");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateIsNotNull() {
            addCriterion("planned_acceptance_date is not null");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateEqualTo(Date value) {
            addCriterionForJDBCDate("planned_acceptance_date =", value, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("planned_acceptance_date <>", value, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateGreaterThan(Date value) {
            addCriterionForJDBCDate("planned_acceptance_date >", value, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("planned_acceptance_date >=", value, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateLessThan(Date value) {
            addCriterionForJDBCDate("planned_acceptance_date <", value, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("planned_acceptance_date <=", value, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateIn(List<Date> values) {
            addCriterionForJDBCDate("planned_acceptance_date in", values, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("planned_acceptance_date not in", values, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("planned_acceptance_date between", value1, value2, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedAcceptanceDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("planned_acceptance_date not between", value1, value2, "plannedAcceptanceDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateIsNull() {
            addCriterion("planned_completion_date is null");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateIsNotNull() {
            addCriterion("planned_completion_date is not null");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateEqualTo(Date value) {
            addCriterionForJDBCDate("planned_completion_date =", value, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("planned_completion_date <>", value, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateGreaterThan(Date value) {
            addCriterionForJDBCDate("planned_completion_date >", value, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("planned_completion_date >=", value, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateLessThan(Date value) {
            addCriterionForJDBCDate("planned_completion_date <", value, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("planned_completion_date <=", value, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateIn(List<Date> values) {
            addCriterionForJDBCDate("planned_completion_date in", values, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("planned_completion_date not in", values, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("planned_completion_date between", value1, value2, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andPlannedCompletionDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("planned_completion_date not between", value1, value2, "plannedCompletionDate");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderIsNull() {
            addCriterion("project_leader is null");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderIsNotNull() {
            addCriterion("project_leader is not null");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderEqualTo(String value) {
            addCriterion("project_leader =", value, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderNotEqualTo(String value) {
            addCriterion("project_leader <>", value, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderGreaterThan(String value) {
            addCriterion("project_leader >", value, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("project_leader >=", value, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderLessThan(String value) {
            addCriterion("project_leader <", value, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderLessThanOrEqualTo(String value) {
            addCriterion("project_leader <=", value, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderLike(String value) {
            addCriterion("project_leader like", value, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderNotLike(String value) {
            addCriterion("project_leader not like", value, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderIn(List<String> values) {
            addCriterion("project_leader in", values, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderNotIn(List<String> values) {
            addCriterion("project_leader not in", values, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderBetween(String value1, String value2) {
            addCriterion("project_leader between", value1, value2, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andProjectLeaderNotBetween(String value1, String value2) {
            addCriterion("project_leader not between", value1, value2, "projectLeader");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("department like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("department not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderIsNull() {
            addCriterion("market_leader is null");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderIsNotNull() {
            addCriterion("market_leader is not null");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderEqualTo(String value) {
            addCriterion("market_leader =", value, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderNotEqualTo(String value) {
            addCriterion("market_leader <>", value, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderGreaterThan(String value) {
            addCriterion("market_leader >", value, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("market_leader >=", value, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderLessThan(String value) {
            addCriterion("market_leader <", value, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderLessThanOrEqualTo(String value) {
            addCriterion("market_leader <=", value, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderLike(String value) {
            addCriterion("market_leader like", value, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderNotLike(String value) {
            addCriterion("market_leader not like", value, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderIn(List<String> values) {
            addCriterion("market_leader in", values, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderNotIn(List<String> values) {
            addCriterion("market_leader not in", values, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderBetween(String value1, String value2) {
            addCriterion("market_leader between", value1, value2, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andMarketLeaderNotBetween(String value1, String value2) {
            addCriterion("market_leader not between", value1, value2, "marketLeader");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalIsNull() {
            addCriterion("expense_or_capital is null");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalIsNotNull() {
            addCriterion("expense_or_capital is not null");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalEqualTo(String value) {
            addCriterion("expense_or_capital =", value, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalNotEqualTo(String value) {
            addCriterion("expense_or_capital <>", value, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalGreaterThan(String value) {
            addCriterion("expense_or_capital >", value, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalGreaterThanOrEqualTo(String value) {
            addCriterion("expense_or_capital >=", value, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalLessThan(String value) {
            addCriterion("expense_or_capital <", value, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalLessThanOrEqualTo(String value) {
            addCriterion("expense_or_capital <=", value, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalLike(String value) {
            addCriterion("expense_or_capital like", value, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalNotLike(String value) {
            addCriterion("expense_or_capital not like", value, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalIn(List<String> values) {
            addCriterion("expense_or_capital in", values, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalNotIn(List<String> values) {
            addCriterion("expense_or_capital not in", values, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalBetween(String value1, String value2) {
            addCriterion("expense_or_capital between", value1, value2, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andExpenseOrCapitalNotBetween(String value1, String value2) {
            addCriterion("expense_or_capital not between", value1, value2, "expenseOrCapital");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityIsNull() {
            addCriterion("connect_buss_opportunity is null");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityIsNotNull() {
            addCriterion("connect_buss_opportunity is not null");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityEqualTo(String value) {
            addCriterion("connect_buss_opportunity =", value, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityNotEqualTo(String value) {
            addCriterion("connect_buss_opportunity <>", value, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityGreaterThan(String value) {
            addCriterion("connect_buss_opportunity >", value, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityGreaterThanOrEqualTo(String value) {
            addCriterion("connect_buss_opportunity >=", value, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityLessThan(String value) {
            addCriterion("connect_buss_opportunity <", value, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityLessThanOrEqualTo(String value) {
            addCriterion("connect_buss_opportunity <=", value, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityLike(String value) {
            addCriterion("connect_buss_opportunity like", value, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityNotLike(String value) {
            addCriterion("connect_buss_opportunity not like", value, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityIn(List<String> values) {
            addCriterion("connect_buss_opportunity in", values, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityNotIn(List<String> values) {
            addCriterion("connect_buss_opportunity not in", values, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityBetween(String value1, String value2) {
            addCriterion("connect_buss_opportunity between", value1, value2, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andConnectBussOpportunityNotBetween(String value1, String value2) {
            addCriterion("connect_buss_opportunity not between", value1, value2, "connectBussOpportunity");
            return (Criteria) this;
        }

        public Criteria andWinBidIdIsNull() {
            addCriterion("win_bid_id is null");
            return (Criteria) this;
        }

        public Criteria andWinBidIdIsNotNull() {
            addCriterion("win_bid_id is not null");
            return (Criteria) this;
        }

        public Criteria andWinBidIdEqualTo(Integer value) {
            addCriterion("win_bid_id =", value, "winBidId");
            return (Criteria) this;
        }

        public Criteria andWinBidIdNotEqualTo(Integer value) {
            addCriterion("win_bid_id <>", value, "winBidId");
            return (Criteria) this;
        }

        public Criteria andWinBidIdGreaterThan(Integer value) {
            addCriterion("win_bid_id >", value, "winBidId");
            return (Criteria) this;
        }

        public Criteria andWinBidIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("win_bid_id >=", value, "winBidId");
            return (Criteria) this;
        }

        public Criteria andWinBidIdLessThan(Integer value) {
            addCriterion("win_bid_id <", value, "winBidId");
            return (Criteria) this;
        }

        public Criteria andWinBidIdLessThanOrEqualTo(Integer value) {
            addCriterion("win_bid_id <=", value, "winBidId");
            return (Criteria) this;
        }

        public Criteria andWinBidIdIn(List<Integer> values) {
            addCriterion("win_bid_id in", values, "winBidId");
            return (Criteria) this;
        }

        public Criteria andWinBidIdNotIn(List<Integer> values) {
            addCriterion("win_bid_id not in", values, "winBidId");
            return (Criteria) this;
        }

        public Criteria andWinBidIdBetween(Integer value1, Integer value2) {
            addCriterion("win_bid_id between", value1, value2, "winBidId");
            return (Criteria) this;
        }

        public Criteria andWinBidIdNotBetween(Integer value1, Integer value2) {
            addCriterion("win_bid_id not between", value1, value2, "winBidId");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentIsNull() {
            addCriterion("project_attachment is null");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentIsNotNull() {
            addCriterion("project_attachment is not null");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentEqualTo(String value) {
            addCriterion("project_attachment =", value, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentNotEqualTo(String value) {
            addCriterion("project_attachment <>", value, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentGreaterThan(String value) {
            addCriterion("project_attachment >", value, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentGreaterThanOrEqualTo(String value) {
            addCriterion("project_attachment >=", value, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentLessThan(String value) {
            addCriterion("project_attachment <", value, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentLessThanOrEqualTo(String value) {
            addCriterion("project_attachment <=", value, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentLike(String value) {
            addCriterion("project_attachment like", value, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentNotLike(String value) {
            addCriterion("project_attachment not like", value, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentIn(List<String> values) {
            addCriterion("project_attachment in", values, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentNotIn(List<String> values) {
            addCriterion("project_attachment not in", values, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentBetween(String value1, String value2) {
            addCriterion("project_attachment between", value1, value2, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andProjectAttachmentNotBetween(String value1, String value2) {
            addCriterion("project_attachment not between", value1, value2, "projectAttachment");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 08 14:38:39 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_info
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}