package nba.clippers.rtwork.db.entity;

import java.math.BigDecimal;

public class BussOpportunity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_opportunity.id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_opportunity.bussop_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String bussopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_opportunity.client_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_opportunity.market_manager_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String marketManagerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_opportunity.bussop_status
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String bussopStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_opportunity.amount
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private BigDecimal amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_opportunity.id
     *
     * @return the value of buss_opportunity.id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_opportunity.id
     *
     * @param id the value for buss_opportunity.id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_opportunity.bussop_name
     *
     * @return the value of buss_opportunity.bussop_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getBussopName() {
        return bussopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_opportunity.bussop_name
     *
     * @param bussopName the value for buss_opportunity.bussop_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setBussopName(String bussopName) {
        this.bussopName = bussopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_opportunity.client_name
     *
     * @return the value of buss_opportunity.client_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_opportunity.client_name
     *
     * @param clientName the value for buss_opportunity.client_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_opportunity.market_manager_name
     *
     * @return the value of buss_opportunity.market_manager_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getMarketManagerName() {
        return marketManagerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_opportunity.market_manager_name
     *
     * @param marketManagerName the value for buss_opportunity.market_manager_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setMarketManagerName(String marketManagerName) {
        this.marketManagerName = marketManagerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_opportunity.bussop_status
     *
     * @return the value of buss_opportunity.bussop_status
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getBussopStatus() {
        return bussopStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_opportunity.bussop_status
     *
     * @param bussopStatus the value for buss_opportunity.bussop_status
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setBussopStatus(String bussopStatus) {
        this.bussopStatus = bussopStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_opportunity.amount
     *
     * @return the value of buss_opportunity.amount
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_opportunity.amount
     *
     * @param amount the value for buss_opportunity.amount
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}