package nba.clippers.rtwork.db.entity;

import java.util.Date;

public class ManagerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.create_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.update_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.id
     *
     * @return the value of manager_info.id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.id
     *
     * @param id the value for manager_info.id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.name
     *
     * @return the value of manager_info.name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.name
     *
     * @param name the value for manager_info.name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.create_at
     *
     * @return the value of manager_info.create_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.create_at
     *
     * @param createAt the value for manager_info.create_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.update_at
     *
     * @return the value of manager_info.update_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.update_at
     *
     * @param updateAt the value for manager_info.update_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}