package nba.clippers.rtwork.db.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ProjectInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_amount
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private BigDecimal projectAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_source
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Integer projectSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_type
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String projectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_level
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String projectLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_initiation_date
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Date projectInitiationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.planned_acceptance_date
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Date plannedAcceptanceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.planned_completion_date
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Date plannedCompletionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_leader
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String projectLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.department
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.market_leader
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String marketLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.expense_or_capital
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String expenseOrCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.connect_buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String connectBussOpportunity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.win_bid_id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Integer winBidId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_attachment
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String projectAttachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.created_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.updated_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_summary
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    private String projectSummary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.id
     *
     * @return the value of project_info.id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.id
     *
     * @param id the value for project_info.id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_name
     *
     * @return the value of project_info.project_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_name
     *
     * @param projectName the value for project_info.project_name
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_amount
     *
     * @return the value of project_info.project_amount
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public BigDecimal getProjectAmount() {
        return projectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_amount
     *
     * @param projectAmount the value for project_info.project_amount
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setProjectAmount(BigDecimal projectAmount) {
        this.projectAmount = projectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_source
     *
     * @return the value of project_info.project_source
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Integer getProjectSource() {
        return projectSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_source
     *
     * @param projectSource the value for project_info.project_source
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setProjectSource(Integer projectSource) {
        this.projectSource = projectSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_type
     *
     * @return the value of project_info.project_type
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_type
     *
     * @param projectType the value for project_info.project_type
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_level
     *
     * @return the value of project_info.project_level
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getProjectLevel() {
        return projectLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_level
     *
     * @param projectLevel the value for project_info.project_level
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setProjectLevel(String projectLevel) {
        this.projectLevel = projectLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_initiation_date
     *
     * @return the value of project_info.project_initiation_date
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Date getProjectInitiationDate() {
        return projectInitiationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_initiation_date
     *
     * @param projectInitiationDate the value for project_info.project_initiation_date
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setProjectInitiationDate(Date projectInitiationDate) {
        this.projectInitiationDate = projectInitiationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.planned_acceptance_date
     *
     * @return the value of project_info.planned_acceptance_date
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Date getPlannedAcceptanceDate() {
        return plannedAcceptanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.planned_acceptance_date
     *
     * @param plannedAcceptanceDate the value for project_info.planned_acceptance_date
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setPlannedAcceptanceDate(Date plannedAcceptanceDate) {
        this.plannedAcceptanceDate = plannedAcceptanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.planned_completion_date
     *
     * @return the value of project_info.planned_completion_date
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Date getPlannedCompletionDate() {
        return plannedCompletionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.planned_completion_date
     *
     * @param plannedCompletionDate the value for project_info.planned_completion_date
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setPlannedCompletionDate(Date plannedCompletionDate) {
        this.plannedCompletionDate = plannedCompletionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_leader
     *
     * @return the value of project_info.project_leader
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getProjectLeader() {
        return projectLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_leader
     *
     * @param projectLeader the value for project_info.project_leader
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setProjectLeader(String projectLeader) {
        this.projectLeader = projectLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.department
     *
     * @return the value of project_info.department
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.department
     *
     * @param department the value for project_info.department
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.market_leader
     *
     * @return the value of project_info.market_leader
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getMarketLeader() {
        return marketLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.market_leader
     *
     * @param marketLeader the value for project_info.market_leader
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setMarketLeader(String marketLeader) {
        this.marketLeader = marketLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.expense_or_capital
     *
     * @return the value of project_info.expense_or_capital
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getExpenseOrCapital() {
        return expenseOrCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.expense_or_capital
     *
     * @param expenseOrCapital the value for project_info.expense_or_capital
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setExpenseOrCapital(String expenseOrCapital) {
        this.expenseOrCapital = expenseOrCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.connect_buss_opportunity
     *
     * @return the value of project_info.connect_buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getConnectBussOpportunity() {
        return connectBussOpportunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.connect_buss_opportunity
     *
     * @param connectBussOpportunity the value for project_info.connect_buss_opportunity
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setConnectBussOpportunity(String connectBussOpportunity) {
        this.connectBussOpportunity = connectBussOpportunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.win_bid_id
     *
     * @return the value of project_info.win_bid_id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Integer getWinBidId() {
        return winBidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.win_bid_id
     *
     * @param winBidId the value for project_info.win_bid_id
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setWinBidId(Integer winBidId) {
        this.winBidId = winBidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_attachment
     *
     * @return the value of project_info.project_attachment
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getProjectAttachment() {
        return projectAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_attachment
     *
     * @param projectAttachment the value for project_info.project_attachment
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setProjectAttachment(String projectAttachment) {
        this.projectAttachment = projectAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.created_at
     *
     * @return the value of project_info.created_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.created_at
     *
     * @param createdAt the value for project_info.created_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.updated_at
     *
     * @return the value of project_info.updated_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.updated_at
     *
     * @param updatedAt the value for project_info.updated_at
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_summary
     *
     * @return the value of project_info.project_summary
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public String getProjectSummary() {
        return projectSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_summary
     *
     * @param projectSummary the value for project_info.project_summary
     *
     * @mbg.generated Thu Aug 08 14:38:39 CST 2024
     */
    public void setProjectSummary(String projectSummary) {
        this.projectSummary = projectSummary;
    }
}